// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	ciliumiov2alpha1 "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/typed/cilium.io/v2alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeCiliumTenants implements CiliumTenantInterface
type fakeCiliumTenants struct {
	*gentype.FakeClientWithList[*v2alpha1.CiliumTenant, *v2alpha1.CiliumTenantList]
	Fake *FakeCiliumV2alpha1
}

func newFakeCiliumTenants(fake *FakeCiliumV2alpha1) ciliumiov2alpha1.CiliumTenantInterface {
	return &fakeCiliumTenants{
		gentype.NewFakeClientWithList[*v2alpha1.CiliumTenant, *v2alpha1.CiliumTenantList](
			fake.Fake,
			"",
			v2alpha1.SchemeGroupVersion.WithResource("ciliumtenants"),
			v2alpha1.SchemeGroupVersion.WithKind("CiliumTenant"),
			func() *v2alpha1.CiliumTenant { return &v2alpha1.CiliumTenant{} },
			func() *v2alpha1.CiliumTenantList { return &v2alpha1.CiliumTenantList{} },
			func(dst, src *v2alpha1.CiliumTenantList) { dst.ListMeta = src.ListMeta },
			func(list *v2alpha1.CiliumTenantList) []*v2alpha1.CiliumTenant {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v2alpha1.CiliumTenantList, items []*v2alpha1.CiliumTenant) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
