// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v2alpha1

import (
	context "context"

	ciliumiov2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// CiliumTenantsGetter has a method to return a CiliumTenantInterface.
// A group's client should implement this interface.
type CiliumTenantsGetter interface {
	CiliumTenants() CiliumTenantInterface
}

// CiliumTenantInterface has methods to work with CiliumTenant resources.
type CiliumTenantInterface interface {
	Create(ctx context.Context, ciliumTenant *ciliumiov2alpha1.CiliumTenant, opts v1.CreateOptions) (*ciliumiov2alpha1.CiliumTenant, error)
	Update(ctx context.Context, ciliumTenant *ciliumiov2alpha1.CiliumTenant, opts v1.UpdateOptions) (*ciliumiov2alpha1.CiliumTenant, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, ciliumTenant *ciliumiov2alpha1.CiliumTenant, opts v1.UpdateOptions) (*ciliumiov2alpha1.CiliumTenant, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*ciliumiov2alpha1.CiliumTenant, error)
	List(ctx context.Context, opts v1.ListOptions) (*ciliumiov2alpha1.CiliumTenantList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *ciliumiov2alpha1.CiliumTenant, err error)
	CiliumTenantExpansion
}

// ciliumTenants implements CiliumTenantInterface
type ciliumTenants struct {
	*gentype.ClientWithList[*ciliumiov2alpha1.CiliumTenant, *ciliumiov2alpha1.CiliumTenantList]
}

// newCiliumTenants returns a CiliumTenants
func newCiliumTenants(c *CiliumV2alpha1Client) *ciliumTenants {
	return &ciliumTenants{
		gentype.NewClientWithList[*ciliumiov2alpha1.CiliumTenant, *ciliumiov2alpha1.CiliumTenantList](
			"ciliumtenants",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *ciliumiov2alpha1.CiliumTenant { return &ciliumiov2alpha1.CiliumTenant{} },
			func() *ciliumiov2alpha1.CiliumTenantList { return &ciliumiov2alpha1.CiliumTenantList{} },
		),
	}
}
