// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v2alpha1

import (
	ciliumiov2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// CiliumTenantLister helps list CiliumTenants.
// All objects returned here must be treated as read-only.
type CiliumTenantLister interface {
	// List lists all CiliumTenants in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*ciliumiov2alpha1.CiliumTenant, err error)
	// Get retrieves the CiliumTenant from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*ciliumiov2alpha1.CiliumTenant, error)
	CiliumTenantListerExpansion
}

// ciliumTenantLister implements the CiliumTenantLister interface.
type ciliumTenantLister struct {
	listers.ResourceIndexer[*ciliumiov2alpha1.CiliumTenant]
}

// NewCiliumTenantLister returns a new CiliumTenantLister.
func NewCiliumTenantLister(indexer cache.Indexer) CiliumTenantLister {
	return &ciliumTenantLister{listers.New[*ciliumiov2alpha1.CiliumTenant](indexer, ciliumiov2alpha1.Resource("ciliumtenant"))}
}
